### ISSUE TITLE
Error when querying all assets `ERR Error: [DecimalError] Invalid argument: null`

### ISSUE THREAD

**Issue by jens1101** [jens1101/asset-register#19]
Full error:
```
gql-1   | ERR Error: [DecimalError] Invalid argument: null
gql-1   |     at new Decimal (file:///app/node_modules/decimal.js/decimal.mjs:4369:13)
gql-1   |     at Object.from (file:///app/workspaces/backend/gql/dist/entities/Image.js:37:28)
gql-1   |     at ApplyValueTransformers.transformFrom (/app/node_modules/typeorm/util/ApplyValueTransformers.js:12:28)
gql-1   |     at PostgresDriver.prepareHydratedValue (/app/node_modules/typeorm/driver/postgres/PostgresDriver.js:492:67)
gql-1   |     at /app/node_modules/typeorm/query-builder/transformer/RawSqlResultsToEntityTransformer.js:132:55
gql-1   |     at Array.forEach (<anonymous>)
gql-1   |     at RawSqlResultsToEntityTransformer.transformColumns (/app/node_modules/typeorm/query-builder/transformer/RawSqlResultsToEntityTransformer.js:118:26)
gql-1   |     at RawSqlResultsToEntityTransformer.transformRawResultsGroup (/app/node_modules/typeorm/query-builder/transformer/RawSqlResultsToEntityTransformer.js:98:33)
gql-1   |     at /app/node_modules/typeorm/query-builder/transformer/RawSqlResultsToEntityTransformer.js:33:33
gql-1   |     at Map.forEach (<anonymous>) {
gql-1   |   path: [ 'assets' ],
gql-1   |   locations: [ { line: 2, column: 3 } ],
gql-1   |   extensions: [Object: null prototype] {}
```

**Comment by jens1101** [comment]
This has been fixed somewhere along the way.
